# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Vishwanath Mayya KC
email: "Vishy007.geek@gmail.com"
description: >
     I am Sr IT Consultant looking for opportunities to work as a Technical Manager & to become a significant contributor in a reputed company that
     provides an innovative environment and opportunities to expose my skills.
about_me: >
     I am experienced Sr Consultant with over 10 + years of total IT experience. Worked in BFSI domain and had been involved in client facing roles at Onsite (in US for 6 years). 
Worked as a Developer, Tech Lead, BSA, SME and currently working as a Technical Manager.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://vishy007-geek.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
linked_in_link: "https://www.linkedin.com/in/vishwanath-mayya-27441a66/"
github_link: "https://github.com/Vishy007-geek"
twitter_username: ""
google_analytics_id: 'UA-117297510-1'
select_options: clear-filters HTML5 CSS3 SCSS javaScript jQuery materialize charts.js React jekyll Ruby-on-Rails Sinatra front-end back-end finished current
sass:
  sass_dir: assets/css/main.css
  style: :nested

gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
